// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package communication

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SecretKillRequest struct {
	Sentence             string   `protobuf:"bytes,1,opt,name=Sentence,proto3" json:"Sentence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretKillRequest) Reset()         { *m = SecretKillRequest{} }
func (m *SecretKillRequest) String() string { return proto.CompactTextString(m) }
func (*SecretKillRequest) ProtoMessage()    {}
func (*SecretKillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *SecretKillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretKillRequest.Unmarshal(m, b)
}
func (m *SecretKillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretKillRequest.Marshal(b, m, deterministic)
}
func (m *SecretKillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretKillRequest.Merge(m, src)
}
func (m *SecretKillRequest) XXX_Size() int {
	return xxx_messageInfo_SecretKillRequest.Size(m)
}
func (m *SecretKillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretKillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretKillRequest proto.InternalMessageInfo

func (m *SecretKillRequest) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

type SecretKillReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretKillReply) Reset()         { *m = SecretKillReply{} }
func (m *SecretKillReply) String() string { return proto.CompactTextString(m) }
func (*SecretKillReply) ProtoMessage()    {}
func (*SecretKillReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *SecretKillReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretKillReply.Unmarshal(m, b)
}
func (m *SecretKillReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretKillReply.Marshal(b, m, deterministic)
}
func (m *SecretKillReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretKillReply.Merge(m, src)
}
func (m *SecretKillReply) XXX_Size() int {
	return xxx_messageInfo_SecretKillReply.Size(m)
}
func (m *SecretKillReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretKillReply.DiscardUnknown(m)
}

var xxx_messageInfo_SecretKillReply proto.InternalMessageInfo

//
// Demande du Client : Demande le déplacement de une ou plusieurs unités
// Argument donné par Client :
//
//* (Coordinates) Point : Variable de type coordonnée servant de destination.
//* ([]string) EntitySelectionUUID : Tableau des identifiants concerné par la requête.
//* (string) Target : Chaine de caractère représentant l'entité qui doit être attaquer.
//Cela peut être :
//** Un identifiant de NPC
//** Un identifiant de batiment
//** Un identifiant de ressource
type RightClickRequest struct {
	Token                string       `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Point                *Coordinates `protobuf:"bytes,2,opt,name=Point,proto3" json:"Point,omitempty"`
	EntitySelectionUUID  []string     `protobuf:"bytes,3,rep,name=EntitySelectionUUID,proto3" json:"EntitySelectionUUID,omitempty"`
	Target               string       `protobuf:"bytes,4,opt,name=Target,proto3" json:"Target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RightClickRequest) Reset()         { *m = RightClickRequest{} }
func (m *RightClickRequest) String() string { return proto.CompactTextString(m) }
func (*RightClickRequest) ProtoMessage()    {}
func (*RightClickRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *RightClickRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RightClickRequest.Unmarshal(m, b)
}
func (m *RightClickRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RightClickRequest.Marshal(b, m, deterministic)
}
func (m *RightClickRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RightClickRequest.Merge(m, src)
}
func (m *RightClickRequest) XXX_Size() int {
	return xxx_messageInfo_RightClickRequest.Size(m)
}
func (m *RightClickRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RightClickRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RightClickRequest proto.InternalMessageInfo

func (m *RightClickRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RightClickRequest) GetPoint() *Coordinates {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *RightClickRequest) GetEntitySelectionUUID() []string {
	if m != nil {
		return m.EntitySelectionUUID
	}
	return nil
}

func (m *RightClickRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

//
// Reponse du Serveur : Un message vide
// Argument donné par Serveur :  Aucun, pas d'information dans le message
type RightClickReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RightClickReply) Reset()         { *m = RightClickReply{} }
func (m *RightClickReply) String() string { return proto.CompactTextString(m) }
func (*RightClickReply) ProtoMessage()    {}
func (*RightClickReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *RightClickReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RightClickReply.Unmarshal(m, b)
}
func (m *RightClickReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RightClickReply.Marshal(b, m, deterministic)
}
func (m *RightClickReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RightClickReply.Merge(m, src)
}
func (m *RightClickReply) XXX_Size() int {
	return xxx_messageInfo_RightClickReply.Size(m)
}
func (m *RightClickReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RightClickReply.DiscardUnknown(m)
}

var xxx_messageInfo_RightClickReply proto.InternalMessageInfo

//
// (float) X : Réel de 32 bits donnant la composante x de la coordonnée sur le carte
// (float) Y : Réel de 32 bits donnant la composante y de la coordonnée sur le carte
type Coordinates struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinates) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

//
// Demande du Client : Demande les actions qui ont été signaler au serveur pour mettre à jour le client.
// Argument donné par Client :
//* (string) Token : Suite de caractère permettant d'identifier et authentifier le client au près du serveur
type AskUpdateRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskUpdateRequest) Reset()         { *m = AskUpdateRequest{} }
func (m *AskUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*AskUpdateRequest) ProtoMessage()    {}
func (*AskUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *AskUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskUpdateRequest.Unmarshal(m, b)
}
func (m *AskUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskUpdateRequest.Marshal(b, m, deterministic)
}
func (m *AskUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskUpdateRequest.Merge(m, src)
}
func (m *AskUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_AskUpdateRequest.Size(m)
}
func (m *AskUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskUpdateRequest proto.InternalMessageInfo

func (m *AskUpdateRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

//
// Reponse du Serveur : Message contenant un tableau des actions * signaler au serveur
// Argument donné par Serveur :
//* ([]UpdateAsked) Array : Tableau contenant les actions entreprissent depuis la dernière mise à jour
//** (int32) Type : Type de l'action décrite dans la suite du message
//** (string) EntityUUID : Entité designé par l'action décrite
//** ([]Param) Arg : Tableau d'argument variable lié au type d'action
//*** (string) Key : Nom de la valeur
//*** (string) Value : Valeur lié à la clé
type AskUpdateReply struct {
	// Si vide rien
	Array                []*UpdateAsked `protobuf:"bytes,1,rep,name=Array,proto3" json:"Array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AskUpdateReply) Reset()         { *m = AskUpdateReply{} }
func (m *AskUpdateReply) String() string { return proto.CompactTextString(m) }
func (*AskUpdateReply) ProtoMessage()    {}
func (*AskUpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *AskUpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskUpdateReply.Unmarshal(m, b)
}
func (m *AskUpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskUpdateReply.Marshal(b, m, deterministic)
}
func (m *AskUpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskUpdateReply.Merge(m, src)
}
func (m *AskUpdateReply) XXX_Size() int {
	return xxx_messageInfo_AskUpdateReply.Size(m)
}
func (m *AskUpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AskUpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_AskUpdateReply proto.InternalMessageInfo

func (m *AskUpdateReply) GetArray() []*UpdateAsked {
	if m != nil {
		return m.Array
	}
	return nil
}

//
// Demande du Client : Demande la création d'un batiment ou d'un npc au serveur.
// Argument donné par Client :
//* (string) Token : Suite de caractère permettant d'identifier et authentifier le client au près du serveur
//* (int) Type : Entier donnant le type de création (0: NPC | 9:Batiment)
//* (int) TypeUnit : Entier donnant le type d'uniter créé
//** NPC : 0 -> villager | 1 -> harvester | 2 -> soldier
//** Batiment : 0 -> auberge | 1 -> caserne | 2 -> établi
//* (Coordinates) Case : Coordonnées d'apparition de l'entité créé
type AskCreationRequest struct {
	Token                string       `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Type                 int32        `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	TypeUnit             int32        `protobuf:"varint,3,opt,name=TypeUnit,proto3" json:"TypeUnit,omitempty"`
	Case                 *Coordinates `protobuf:"bytes,4,opt,name=Case,proto3" json:"Case,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AskCreationRequest) Reset()         { *m = AskCreationRequest{} }
func (m *AskCreationRequest) String() string { return proto.CompactTextString(m) }
func (*AskCreationRequest) ProtoMessage()    {}
func (*AskCreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *AskCreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskCreationRequest.Unmarshal(m, b)
}
func (m *AskCreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskCreationRequest.Marshal(b, m, deterministic)
}
func (m *AskCreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskCreationRequest.Merge(m, src)
}
func (m *AskCreationRequest) XXX_Size() int {
	return xxx_messageInfo_AskCreationRequest.Size(m)
}
func (m *AskCreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskCreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskCreationRequest proto.InternalMessageInfo

func (m *AskCreationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AskCreationRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *AskCreationRequest) GetTypeUnit() int32 {
	if m != nil {
		return m.TypeUnit
	}
	return 0
}

func (m *AskCreationRequest) GetCase() *Coordinates {
	if m != nil {
		return m.Case
	}
	return nil
}

//
// Reponse du Serveur : Valide ou pas la création d'un batiment ou d'un npc. Les données sont transmisses dans le AskUpdate
// Argument donné par Serveur :
//* (bool) Validation : Booléen valant vrai si la création est validée, sinon faux.
type AskCreationReply struct {
	Validation           bool     `protobuf:"varint,1,opt,name=Validation,proto3" json:"Validation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskCreationReply) Reset()         { *m = AskCreationReply{} }
func (m *AskCreationReply) String() string { return proto.CompactTextString(m) }
func (*AskCreationReply) ProtoMessage()    {}
func (*AskCreationReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *AskCreationReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskCreationReply.Unmarshal(m, b)
}
func (m *AskCreationReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskCreationReply.Marshal(b, m, deterministic)
}
func (m *AskCreationReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskCreationReply.Merge(m, src)
}
func (m *AskCreationReply) XXX_Size() int {
	return xxx_messageInfo_AskCreationReply.Size(m)
}
func (m *AskCreationReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AskCreationReply.DiscardUnknown(m)
}

var xxx_messageInfo_AskCreationReply proto.InternalMessageInfo

func (m *AskCreationReply) GetValidation() bool {
	if m != nil {
		return m.Validation
	}
	return false
}

//
// 0 : Création d'un NPC
//* EntityUUID : Identifiant de l'entité créé
//* Arg :
//** Key :
//- "pv" -> (int) Point de vie
//- "x" -> (float) Coordonnée x
//- "y" -> (float) Coordonnée y
//- "vitesse" -> (int) Vitesse de déplacement
//- "type" -> (int) Type de NPC (0:villager | 1:harvester | 2:soldier)
//- "damage" -> (int) Dégats qu'inflige le NPC
//- "vue" -> (int) Distance de vue du NPC
//- "portee" -> (int) Distance de la portée d'attaque
//** Value : Valeur en fonction de la donnée
//
// 1 : Destruction d'un NPC
//* EntityUUID : Identifiant de l'entité conserné
//* Arg : Vide
//
// 2 : Modification d'un NPC
//* EntityUUID : Identifiant de l'entité conserné
//* Arg :
//** Key :
//- "pv" -> (int) Point de vie
//- "x" -> (float) Coordonnée x
//- "y" -> (float) Coordonnée y
//- "destX" -> (float) Destination coordonnée x (-1 si pas de chemin)
//- "destY" -> (float) Destination coordonnée y (-1 si pas de chemin)
//- "vitesse" -> (int) Vitesse de déplacement
//- "vue" -> (int) Distance de vue du NPC
//- "portee" -> (int) Distance de la portée d'attaque
//** Value : Valeur en fonction de la donnée
//
// 3 : Mise à jour des ressource d'un joueur
//* EntityUUID : Identifiant du joueur conserné
//* Arg :
//** Key :
//- "water" -> (int) Eau
//- "wood" -> (int) Bois
//- "stone" -> (int) Pierre
//- "food" -> (int) Nourriture
//** Value : Nombre d'élément que possède le joueur
//
// 4 : Endommagement d'une ressource
//* EntityUUID : Coordonnée de la ressource conserné
//* Arg :
//** Key :
//- "x" -> (float) Coordonnée x
//- "y" -> (float) Coordonnée y
//- "pv" -> (int) Nouveau point de vie
//** Value : Valeur en fonction de la donnée
//
// 5 : Destruction d'une ressource
//* EntityUUID : Coordonnée de la ressource conserné
//* Arg :
//** Key :
//- "x" -> (float) Coordonnée x
//- "y" -> (float) Coordonnée y
//** Value : Valeur en fonction de la donnée
//
// 6 : Création d'une ressource
//* EntityUUID : Coordonnée de la ressource conserné
//* Arg :
//** Key :
//- "x" -> (float) Coordonnée x
//- "y" -> (float) Coordonnée y
//- "pv" -> (int) Point de vie
//- "type" -> (int) Type
//- "id" -> (string) ID
//** Value : Valeur en fonction de la donnée
//- "type" -> "0"->Eau | "1"->Bois | "2"->Pierre | "3"->Nourriture
//
// 7 : Endommagement d'un bâtiment
//* EntityUUID : Identifiant du bâtiment conserné
//* Arg :
//** Key :
//- "pv" -> (int) Nouveau point de vie
//** Value : Valeur en fonction de la donnée
//
// 8 : Destruction d'un bâtiment
//* EntityUUID : Identifiant du bâtiment conserné
//* Arg : Vide
//
// 9 : Création d'un bâtiment
//* EntityUUID : Identifiant du bâtiment conserné
//* Arg :
//** Key :
//- "x" -> (float) Coordonnée x
//- "y" -> (float) Coordonnée y
//- "pv" -> (int) Point de vie
//- "type" -> (int) Type
//- "uuid" -> (string) PlayerUUID
//** Value : Valeur en fonction de la donnée
//
// 10 : Fin du jeu
//* EntityUUID : Vide
//* Arg : Vide
type UpdateAsked struct {
	Type                 int32    `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	EntityUUID           string   `protobuf:"bytes,2,opt,name=EntityUUID,proto3" json:"EntityUUID,omitempty"`
	Arg                  []*Param `protobuf:"bytes,3,rep,name=Arg,proto3" json:"Arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAsked) Reset()         { *m = UpdateAsked{} }
func (m *UpdateAsked) String() string { return proto.CompactTextString(m) }
func (*UpdateAsked) ProtoMessage()    {}
func (*UpdateAsked) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *UpdateAsked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAsked.Unmarshal(m, b)
}
func (m *UpdateAsked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAsked.Marshal(b, m, deterministic)
}
func (m *UpdateAsked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAsked.Merge(m, src)
}
func (m *UpdateAsked) XXX_Size() int {
	return xxx_messageInfo_UpdateAsked.Size(m)
}
func (m *UpdateAsked) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAsked.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAsked proto.InternalMessageInfo

func (m *UpdateAsked) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *UpdateAsked) GetEntityUUID() string {
	if m != nil {
		return m.EntityUUID
	}
	return ""
}

func (m *UpdateAsked) GetArg() []*Param {
	if m != nil {
		return m.Arg
	}
	return nil
}

type Param struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Param) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "communication.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "communication.HelloReply")
	proto.RegisterType((*SecretKillRequest)(nil), "communication.SecretKillRequest")
	proto.RegisterType((*SecretKillReply)(nil), "communication.SecretKillReply")
	proto.RegisterType((*RightClickRequest)(nil), "communication.RightClickRequest")
	proto.RegisterType((*RightClickReply)(nil), "communication.RightClickReply")
	proto.RegisterType((*Coordinates)(nil), "communication.Coordinates")
	proto.RegisterType((*AskUpdateRequest)(nil), "communication.AskUpdateRequest")
	proto.RegisterType((*AskUpdateReply)(nil), "communication.AskUpdateReply")
	proto.RegisterType((*AskCreationRequest)(nil), "communication.AskCreationRequest")
	proto.RegisterType((*AskCreationReply)(nil), "communication.AskCreationReply")
	proto.RegisterType((*UpdateAsked)(nil), "communication.UpdateAsked")
	proto.RegisterType((*Param)(nil), "communication.Param")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x94, 0x4d, 0x6f, 0xda, 0x4c,
	0x10, 0xc7, 0xb3, 0x18, 0x47, 0x61, 0xe0, 0x79, 0x1a, 0xb6, 0x51, 0xe5, 0xba, 0x2a, 0x71, 0xf7,
	0x50, 0xd1, 0x0b, 0x41, 0xf4, 0x13, 0x50, 0x52, 0xa9, 0x51, 0xd4, 0x0a, 0x2d, 0x10, 0x25, 0xc7,
	0xad, 0x59, 0xd1, 0x15, 0xc6, 0x76, 0xd7, 0xcb, 0xc1, 0xf7, 0x9e, 0xfa, 0x25, 0x7a, 0xea, 0xf7,
	0xac, 0x76, 0xcc, 0x8b, 0x6b, 0x28, 0x27, 0x76, 0x76, 0x7f, 0xcc, 0xfc, 0xe7, 0xcd, 0xd0, 0xd0,
	0x69, 0xd8, 0x4b, 0x75, 0x62, 0x12, 0xfa, 0x5f, 0x98, 0xac, 0x56, 0xeb, 0x58, 0x85, 0xc2, 0xa8,
	0x24, 0x66, 0x0c, 0x5a, 0x9f, 0x64, 0x14, 0x25, 0x5c, 0x7e, 0x5f, 0xcb, 0xcc, 0x50, 0x0a, 0xf5,
	0x2f, 0x62, 0x25, 0x3d, 0x12, 0x90, 0x6e, 0x83, 0xe3, 0x99, 0x05, 0x00, 0x1b, 0x26, 0x8d, 0xf2,
	0xa3, 0xc4, 0x0d, 0xb4, 0x27, 0x32, 0xd4, 0xd2, 0xdc, 0xab, 0x28, 0xda, 0xba, 0xf2, 0xe1, 0x62,
	0x22, 0x63, 0x23, 0xe3, 0x70, 0x0b, 0xef, 0x6c, 0xd6, 0x86, 0x67, 0xe5, 0x3f, 0xa4, 0x51, 0xce,
	0x7e, 0x13, 0x68, 0x73, 0xb5, 0xf8, 0x66, 0x46, 0x91, 0x0a, 0x97, 0x5b, 0x27, 0x57, 0xe0, 0x4e,
	0x93, 0xa5, 0x8c, 0x37, 0x1e, 0x0a, 0x83, 0xf6, 0xc1, 0x1d, 0x27, 0x2a, 0x36, 0x5e, 0x2d, 0x20,
	0xdd, 0xe6, 0xc0, 0xef, 0xfd, 0x95, 0x54, 0x6f, 0x94, 0x24, 0x7a, 0xae, 0x62, 0x61, 0x64, 0xc6,
	0x0b, 0x90, 0xf6, 0xe1, 0xf9, 0xc7, 0xd8, 0x28, 0x93, 0x4f, 0x64, 0x24, 0x43, 0x4b, 0xcd, 0x66,
	0x77, 0xb7, 0x9e, 0x13, 0x38, 0xdd, 0x06, 0x3f, 0xf6, 0x44, 0x5f, 0xc0, 0xf9, 0x54, 0xe8, 0x85,
	0x34, 0x5e, 0x1d, 0x43, 0x6f, 0x2c, 0x2b, 0xbd, 0x2c, 0xd3, 0x4a, 0x7f, 0x07, 0xcd, 0x52, 0x48,
	0xda, 0x02, 0xf2, 0x88, 0x7a, 0x6b, 0x9c, 0x3c, 0x5a, 0xeb, 0x09, 0x75, 0xd6, 0x38, 0x79, 0x62,
	0x5d, 0xb8, 0x1c, 0x66, 0xcb, 0x59, 0x3a, 0x17, 0x46, 0x9e, 0xcc, 0x91, 0x7d, 0x80, 0xff, 0x4b,
	0xa4, 0xad, 0x7c, 0x1f, 0xdc, 0xa1, 0xd6, 0x22, 0xf7, 0x48, 0xe0, 0x1c, 0xc9, 0xba, 0x40, 0x87,
	0xd9, 0x52, 0xce, 0x79, 0x01, 0xb2, 0x9f, 0x04, 0xe8, 0x30, 0x5b, 0x8e, 0xb4, 0x44, 0xe4, 0x74,
	0x51, 0x29, 0xd4, 0xa7, 0x79, 0x2a, 0x51, 0xab, 0xcb, 0xf1, 0x6c, 0x7b, 0x68, 0x7f, 0x67, 0xb1,
	0x32, 0x9e, 0x83, 0xf7, 0x3b, 0x9b, 0xf6, 0xa0, 0x3e, 0x12, 0x99, 0xc4, 0xf2, 0x9c, 0xee, 0x01,
	0x72, 0x6c, 0x80, 0xa9, 0xef, 0xb5, 0xd8, 0x94, 0x3a, 0x00, 0x0f, 0x22, 0x52, 0x73, 0xbc, 0x42,
	0x39, 0x17, 0xbc, 0x74, 0xc3, 0x14, 0x34, 0x4b, 0x69, 0xed, 0x24, 0x92, 0x92, 0xc4, 0x0e, 0x40,
	0xd1, 0x3e, 0x6c, 0x68, 0x0d, 0x33, 0x2a, 0xdd, 0xd0, 0xb7, 0xe0, 0x0c, 0xf5, 0x02, 0x3b, 0xdd,
	0x1c, 0x5c, 0x55, 0x54, 0x8e, 0x85, 0x16, 0x2b, 0x6e, 0x01, 0x76, 0x03, 0x2e, 0x5a, 0xf4, 0x12,
	0x9c, 0x7b, 0x99, 0x6f, 0x6a, 0x63, 0x8f, 0xb6, 0x5e, 0x0f, 0x22, 0x5a, 0xcb, 0x8d, 0xf7, 0xc2,
	0x18, 0xfc, 0x22, 0xe0, 0xe2, 0x5e, 0xd0, 0x5b, 0xb8, 0x98, 0x88, 0xbc, 0x38, 0xbf, 0xaa, 0x44,
	0x28, 0x6f, 0x97, 0xff, 0xf2, 0xf8, 0xa3, 0x9d, 0xa1, 0x33, 0x3a, 0x06, 0xd8, 0xef, 0x04, 0x0d,
	0x2a, 0xe8, 0xc1, 0x7e, 0xf9, 0x9d, 0x13, 0x04, 0x7a, 0x1c, 0xfc, 0xa8, 0x41, 0xeb, 0x2e, 0x36,
	0x52, 0x0b, 0x1c, 0xeb, 0xcc, 0x86, 0xd8, 0xcf, 0xee, 0x41, 0x88, 0x83, 0xed, 0x3b, 0x08, 0x51,
	0x1d, 0xfc, 0x33, 0xfa, 0x19, 0x1a, 0xbb, 0x29, 0xa5, 0xd7, 0x15, 0xbc, 0x3a, 0xe9, 0xfe, 0xeb,
	0x7f, 0x03, 0x85, 0xbb, 0x09, 0x34, 0x4b, 0x33, 0x42, 0xdf, 0x1c, 0xf2, 0x95, 0x59, 0xf6, 0xaf,
	0x4f, 0x21, 0xe8, 0xf4, 0xeb, 0x39, 0x7e, 0xf9, 0xde, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x8a,
	0x46, 0x4f, 0x94, 0x06, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	// Fonction servant juste au test de connection
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// Fonction qui sert à tué secrètement le serveur
	SecretKill(ctx context.Context, in *SecretKillRequest, opts ...grpc.CallOption) (*SecretKillReply, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/communication.Hello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) SecretKill(ctx context.Context, in *SecretKillRequest, opts ...grpc.CallOption) (*SecretKillReply, error) {
	out := new(SecretKillReply)
	err := c.cc.Invoke(ctx, "/communication.Hello/SecretKill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	// Fonction servant juste au test de connection
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// Fonction qui sert à tué secrètement le serveur
	SecretKill(context.Context, *SecretKillRequest) (*SecretKillReply, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_SecretKill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretKillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SecretKill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Hello/SecretKill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SecretKill(ctx, req.(*SecretKillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
		{
			MethodName: "SecretKill",
			Handler:    _Hello_SecretKill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// InteractionsClient is the client API for Interactions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InteractionsClient interface {
	// Fonction transmettant un click du client au serveur
	RightClick(ctx context.Context, in *RightClickRequest, opts ...grpc.CallOption) (*RightClickReply, error)
	// Fonction permettant au client de demander les mises à jour
	AskUpdate(ctx context.Context, in *AskUpdateRequest, opts ...grpc.CallOption) (*AskUpdateReply, error)
	// Fonction de création(npc ou batiment)
	AskCreation(ctx context.Context, in *AskCreationRequest, opts ...grpc.CallOption) (*AskCreationReply, error)
}

type interactionsClient struct {
	cc *grpc.ClientConn
}

func NewInteractionsClient(cc *grpc.ClientConn) InteractionsClient {
	return &interactionsClient{cc}
}

func (c *interactionsClient) RightClick(ctx context.Context, in *RightClickRequest, opts ...grpc.CallOption) (*RightClickReply, error) {
	out := new(RightClickReply)
	err := c.cc.Invoke(ctx, "/communication.Interactions/RightClick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsClient) AskUpdate(ctx context.Context, in *AskUpdateRequest, opts ...grpc.CallOption) (*AskUpdateReply, error) {
	out := new(AskUpdateReply)
	err := c.cc.Invoke(ctx, "/communication.Interactions/AskUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsClient) AskCreation(ctx context.Context, in *AskCreationRequest, opts ...grpc.CallOption) (*AskCreationReply, error) {
	out := new(AskCreationReply)
	err := c.cc.Invoke(ctx, "/communication.Interactions/AskCreation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionsServer is the server API for Interactions service.
type InteractionsServer interface {
	// Fonction transmettant un click du client au serveur
	RightClick(context.Context, *RightClickRequest) (*RightClickReply, error)
	// Fonction permettant au client de demander les mises à jour
	AskUpdate(context.Context, *AskUpdateRequest) (*AskUpdateReply, error)
	// Fonction de création(npc ou batiment)
	AskCreation(context.Context, *AskCreationRequest) (*AskCreationReply, error)
}

func RegisterInteractionsServer(s *grpc.Server, srv InteractionsServer) {
	s.RegisterService(&_Interactions_serviceDesc, srv)
}

func _Interactions_RightClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RightClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServer).RightClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Interactions/RightClick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServer).RightClick(ctx, req.(*RightClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interactions_AskUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServer).AskUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Interactions/AskUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServer).AskUpdate(ctx, req.(*AskUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interactions_AskCreation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServer).AskCreation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Interactions/AskCreation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServer).AskCreation(ctx, req.(*AskCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Interactions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.Interactions",
	HandlerType: (*InteractionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RightClick",
			Handler:    _Interactions_RightClick_Handler,
		},
		{
			MethodName: "AskUpdate",
			Handler:    _Interactions_AskUpdate_Handler,
		},
		{
			MethodName: "AskCreation",
			Handler:    _Interactions_AskCreation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
