// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package communication

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

type HelloReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

// Messages liés à RightClick
type RightClickRequest struct {
	Coordinates          *Coordinates `protobuf:"bytes,1,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	EntitySelectionUUID  []string     `protobuf:"bytes,2,rep,name=entitySelectionUUID,proto3" json:"entitySelectionUUID,omitempty"`
	Target               string       `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RightClickRequest) Reset()         { *m = RightClickRequest{} }
func (m *RightClickRequest) String() string { return proto.CompactTextString(m) }
func (*RightClickRequest) ProtoMessage()    {}
func (*RightClickRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *RightClickRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RightClickRequest.Unmarshal(m, b)
}
func (m *RightClickRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RightClickRequest.Marshal(b, m, deterministic)
}
func (m *RightClickRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RightClickRequest.Merge(m, src)
}
func (m *RightClickRequest) XXX_Size() int {
	return xxx_messageInfo_RightClickRequest.Size(m)
}
func (m *RightClickRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RightClickRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RightClickRequest proto.InternalMessageInfo

func (m *RightClickRequest) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *RightClickRequest) GetEntitySelectionUUID() []string {
	if m != nil {
		return m.EntitySelectionUUID
	}
	return nil
}

func (m *RightClickRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type RightClickReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RightClickReply) Reset()         { *m = RightClickReply{} }
func (m *RightClickReply) String() string { return proto.CompactTextString(m) }
func (*RightClickReply) ProtoMessage()    {}
func (*RightClickReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *RightClickReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RightClickReply.Unmarshal(m, b)
}
func (m *RightClickReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RightClickReply.Marshal(b, m, deterministic)
}
func (m *RightClickReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RightClickReply.Merge(m, src)
}
func (m *RightClickReply) XXX_Size() int {
	return xxx_messageInfo_RightClickReply.Size(m)
}
func (m *RightClickReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RightClickReply.DiscardUnknown(m)
}

var xxx_messageInfo_RightClickReply proto.InternalMessageInfo

// Message liés à MoveTo
type AskUpdateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskUpdateRequest) Reset()         { *m = AskUpdateRequest{} }
func (m *AskUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*AskUpdateRequest) ProtoMessage()    {}
func (*AskUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *AskUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskUpdateRequest.Unmarshal(m, b)
}
func (m *AskUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskUpdateRequest.Marshal(b, m, deterministic)
}
func (m *AskUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskUpdateRequest.Merge(m, src)
}
func (m *AskUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_AskUpdateRequest.Size(m)
}
func (m *AskUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskUpdateRequest proto.InternalMessageInfo

type AskUpdateReply struct {
	// Si vide rien
	Array                []*UpdateAsked `protobuf:"bytes,1,rep,name=array,proto3" json:"array,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AskUpdateReply) Reset()         { *m = AskUpdateReply{} }
func (m *AskUpdateReply) String() string { return proto.CompactTextString(m) }
func (*AskUpdateReply) ProtoMessage()    {}
func (*AskUpdateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *AskUpdateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskUpdateReply.Unmarshal(m, b)
}
func (m *AskUpdateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskUpdateReply.Marshal(b, m, deterministic)
}
func (m *AskUpdateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskUpdateReply.Merge(m, src)
}
func (m *AskUpdateReply) XXX_Size() int {
	return xxx_messageInfo_AskUpdateReply.Size(m)
}
func (m *AskUpdateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AskUpdateReply.DiscardUnknown(m)
}

var xxx_messageInfo_AskUpdateReply proto.InternalMessageInfo

func (m *AskUpdateReply) GetArray() []*UpdateAsked {
	if m != nil {
		return m.Array
	}
	return nil
}

// Message de structure du service Interactions
type Coordinates struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinates) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

//
//type: list
//- 0: vide
//- 1: case carte
//- type: int
//- 0: eau
//- 1: herbe
//- 2: case ressource
//- type: int
//- 0: bois
//- 1: pierre
//- 3: case entité
//- x: int
//- y: int
//- xDest: int
//- yDest: int
//- hp: int
//- hpMax: int
//- name: string
//
type UpdateAsked struct {
	Type                 int32    `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	EntityUUID           string   `protobuf:"bytes,2,opt,name=entityUUID,proto3" json:"entityUUID,omitempty"`
	Arg                  []*Param `protobuf:"bytes,3,rep,name=arg,proto3" json:"arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAsked) Reset()         { *m = UpdateAsked{} }
func (m *UpdateAsked) String() string { return proto.CompactTextString(m) }
func (*UpdateAsked) ProtoMessage()    {}
func (*UpdateAsked) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *UpdateAsked) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAsked.Unmarshal(m, b)
}
func (m *UpdateAsked) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAsked.Marshal(b, m, deterministic)
}
func (m *UpdateAsked) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAsked.Merge(m, src)
}
func (m *UpdateAsked) XXX_Size() int {
	return xxx_messageInfo_UpdateAsked.Size(m)
}
func (m *UpdateAsked) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAsked.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAsked proto.InternalMessageInfo

func (m *UpdateAsked) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *UpdateAsked) GetEntityUUID() string {
	if m != nil {
		return m.EntityUUID
	}
	return ""
}

func (m *UpdateAsked) GetArg() []*Param {
	if m != nil {
		return m.Arg
	}
	return nil
}

type Param struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Param) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "communication.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "communication.HelloReply")
	proto.RegisterType((*RightClickRequest)(nil), "communication.RightClickRequest")
	proto.RegisterType((*RightClickReply)(nil), "communication.RightClickReply")
	proto.RegisterType((*AskUpdateRequest)(nil), "communication.AskUpdateRequest")
	proto.RegisterType((*AskUpdateReply)(nil), "communication.AskUpdateReply")
	proto.RegisterType((*Coordinates)(nil), "communication.Coordinates")
	proto.RegisterType((*UpdateAsked)(nil), "communication.UpdateAsked")
	proto.RegisterType((*Param)(nil), "communication.Param")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xc1, 0x8e, 0xda, 0x30,
	0x10, 0x86, 0x6b, 0xd2, 0xa0, 0x66, 0x92, 0x52, 0x98, 0xa2, 0x2a, 0x4d, 0x55, 0x1a, 0xe5, 0x50,
	0xd1, 0x0b, 0x45, 0xf4, 0xda, 0x0b, 0x85, 0x43, 0x39, 0x20, 0x21, 0x23, 0x1e, 0xc0, 0x0d, 0x16,
	0x8d, 0x12, 0x92, 0xd4, 0x31, 0x15, 0x7e, 0x96, 0x7d, 0x88, 0x7d, 0xc5, 0x55, 0x9c, 0xec, 0x92,
	0xcd, 0xb2, 0x7b, 0x9b, 0xdf, 0xfe, 0x98, 0x99, 0x9f, 0xdf, 0x01, 0x4b, 0xe4, 0xe1, 0x24, 0x17,
	0x99, 0xcc, 0xf0, 0x6d, 0x98, 0x1d, 0x8f, 0xa7, 0x34, 0x0a, 0x99, 0x8c, 0xb2, 0x34, 0xe8, 0x81,
	0xf3, 0x9b, 0x27, 0x49, 0x46, 0xf9, 0xbf, 0x13, 0x2f, 0x64, 0xe0, 0x00, 0xd4, 0x3a, 0x4f, 0x54,
	0x70, 0x43, 0x60, 0x40, 0xa3, 0xc3, 0x5f, 0xb9, 0x48, 0xa2, 0x30, 0xae, 0x19, 0xfc, 0x09, 0x76,
	0x98, 0x65, 0x62, 0x1f, 0xa5, 0x4c, 0xf2, 0xc2, 0x25, 0x3e, 0x19, 0xdb, 0x33, 0x6f, 0xf2, 0xa8,
	0xf1, 0x64, 0x71, 0x21, 0x68, 0x13, 0xc7, 0x29, 0xbc, 0xe7, 0xa9, 0x8c, 0xa4, 0xda, 0xf2, 0x84,
	0x87, 0x25, 0xbb, 0xdb, 0xad, 0x96, 0x6e, 0xc7, 0x37, 0xc6, 0x16, 0xbd, 0x76, 0x85, 0x1f, 0xa0,
	0x2b, 0x99, 0x38, 0x70, 0xe9, 0x1a, 0x3e, 0x19, 0x5b, 0xb4, 0x56, 0xc1, 0x00, 0xde, 0x35, 0x97,
	0x2b, 0x17, 0x46, 0xe8, 0xcf, 0x8b, 0x78, 0x97, 0xef, 0x99, 0xe4, 0xf7, 0x96, 0x7e, 0x41, 0xaf,
	0x71, 0x96, 0x27, 0x0a, 0xa7, 0x60, 0x32, 0x21, 0x98, 0x72, 0x89, 0x6f, 0x5c, 0x59, 0xbd, 0x42,
	0xe7, 0x45, 0xcc, 0xf7, 0xb4, 0x02, 0x83, 0x6f, 0x60, 0x37, 0x0c, 0xa1, 0x03, 0xe4, 0xac, 0x7d,
	0x9b, 0x94, 0x9c, 0x4b, 0xa5, 0xdc, 0x4e, 0xa5, 0x54, 0x10, 0x81, 0xdd, 0x68, 0x80, 0x08, 0xaf,
	0xa5, 0xca, 0x79, 0x4d, 0xeb, 0x1a, 0x47, 0x00, 0x95, 0xcf, 0xda, 0x79, 0x69, 0xaa, 0x71, 0x82,
	0x5f, 0xc1, 0x60, 0xe2, 0xe0, 0x1a, 0x7a, 0xbb, 0x61, 0x6b, 0xbb, 0x0d, 0x13, 0xec, 0x48, 0x4b,
	0x20, 0xf8, 0x0e, 0xa6, 0x56, 0xd8, 0x07, 0x23, 0xe6, 0x4a, 0xcf, 0xb0, 0x68, 0x59, 0xe2, 0x10,
	0xcc, 0xff, 0x2c, 0x39, 0xf1, 0xba, 0x7b, 0x25, 0x66, 0x6b, 0x30, 0x75, 0xba, 0xb8, 0x84, 0x37,
	0x5b, 0xa6, 0xaa, 0xfa, 0x53, 0x6b, 0x40, 0xf3, 0x3d, 0x78, 0x1f, 0xaf, 0x5f, 0x96, 0xff, 0xf5,
	0xab, 0xd9, 0x2d, 0x01, 0x67, 0x95, 0x4a, 0x2e, 0x98, 0x0e, 0xab, 0xc0, 0x0d, 0xc0, 0x25, 0x11,
	0xf4, 0x5b, 0xbf, 0x7d, 0xf2, 0x92, 0xbc, 0xd1, 0x0b, 0x84, 0x1e, 0x81, 0x6b, 0xb0, 0x1e, 0xc2,
	0xc3, 0x2f, 0x2d, 0xbc, 0x1d, 0xb5, 0xf7, 0xf9, 0x79, 0x40, 0xb7, 0xfb, 0xd3, 0xd5, 0x1f, 0xc1,
	0x8f, 0xbb, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xb7, 0x7f, 0x46, 0x11, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	// Fonction servant juste au test de connection
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/communication.Hello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	// Fonction servant juste au test de connection
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

// InteractionsClient is the client API for Interactions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InteractionsClient interface {
	// Fonction transmettant un click du client au serveur
	RightClick(ctx context.Context, in *RightClickRequest, opts ...grpc.CallOption) (*RightClickReply, error)
	// Fonction permettant au client de demander les mises à jour
	AskUpdate(ctx context.Context, in *AskUpdateRequest, opts ...grpc.CallOption) (*AskUpdateReply, error)
}

type interactionsClient struct {
	cc *grpc.ClientConn
}

func NewInteractionsClient(cc *grpc.ClientConn) InteractionsClient {
	return &interactionsClient{cc}
}

func (c *interactionsClient) RightClick(ctx context.Context, in *RightClickRequest, opts ...grpc.CallOption) (*RightClickReply, error) {
	out := new(RightClickReply)
	err := c.cc.Invoke(ctx, "/communication.Interactions/RightClick", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interactionsClient) AskUpdate(ctx context.Context, in *AskUpdateRequest, opts ...grpc.CallOption) (*AskUpdateReply, error) {
	out := new(AskUpdateReply)
	err := c.cc.Invoke(ctx, "/communication.Interactions/AskUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteractionsServer is the server API for Interactions service.
type InteractionsServer interface {
	// Fonction transmettant un click du client au serveur
	RightClick(context.Context, *RightClickRequest) (*RightClickReply, error)
	// Fonction permettant au client de demander les mises à jour
	AskUpdate(context.Context, *AskUpdateRequest) (*AskUpdateReply, error)
}

func RegisterInteractionsServer(s *grpc.Server, srv InteractionsServer) {
	s.RegisterService(&_Interactions_serviceDesc, srv)
}

func _Interactions_RightClick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RightClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServer).RightClick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Interactions/RightClick",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServer).RightClick(ctx, req.(*RightClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interactions_AskUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteractionsServer).AskUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Interactions/AskUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteractionsServer).AskUpdate(ctx, req.(*AskUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Interactions_serviceDesc = grpc.ServiceDesc{
	ServiceName: "communication.Interactions",
	HandlerType: (*InteractionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RightClick",
			Handler:    _Interactions_RightClick_Handler,
		},
		{
			MethodName: "AskUpdate",
			Handler:    _Interactions_AskUpdate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
